CREATE TABLE `appointments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workspaceId` int NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientPhone` varchar(50),
	`clientEmail` varchar(255),
	`clientAddress` varchar(500),
	`serviceTitle` varchar(255) NOT NULL,
	`serviceNotes` text,
	`scheduledAt` bigint NOT NULL,
	`durationMins` int DEFAULT 60,
	`status` varchar(50) DEFAULT 'confirmed',
	`jobNotes` text,
	`jobAmount` varchar(50),
	`completedAt` bigint,
	`paymentMethod` varchar(50),
	`invoiceRef` varchar(100),
	`smsConfirmSent` tinyint DEFAULT 0,
	`smsReminderSent` tinyint DEFAULT 0,
	`smsOnWaySent` tinyint DEFAULT 0,
	`smsThankYouSent` tinyint DEFAULT 0,
	`reviewRequestAt` bigint,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `appointments_id` PRIMARY KEY(`id`)
);
