import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center gap-2.5 hover:opacity-80 transition-opacity">
              <img src="/manus-storage/blastly-icon-512_d2809e7c.png" alt="Blastly" className="h-12 w-12 rounded-xl object-cover cursor-pointer" />
              <span className="text-2xl font-black tracking-tight">Blastly</span>
            </Link>
          </div>
        </div>
      </nav>

      <div className="container max-w-3xl mx-auto py-12 px-4">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: April 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-foreground">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">By accessing or using Blastly ("the Service") at blastly.ai, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">Blastly is an AI-powered social media marketing platform that helps businesses create, schedule, and optimise social media content across multiple platforms. The Service includes AI content generation, social media scheduling, analytics, audit tools, and video creation features.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Account Registration</h2>
            <p className="text-muted-foreground leading-relaxed">To use certain features of the Service, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information when creating your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Subscription and Payment</h2>
            <p className="text-muted-foreground leading-relaxed">Blastly offers paid subscription plans (Starter, Pro, Agency) billed monthly. All payments are processed securely through Stripe. Subscriptions automatically renew unless cancelled before the renewal date. Refunds are provided at our discretion within 7 days of purchase if the Service has not been substantially used.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed">You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1 text-muted-foreground">
              <li>Generate spam, misleading, or fraudulent content</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon the intellectual property rights of others</li>
              <li>Distribute malware or engage in any harmful activities</li>
              <li>Attempt to gain unauthorised access to our systems</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. AI-Generated Content</h2>
            <p className="text-muted-foreground leading-relaxed">Content generated by Blastly's AI tools is provided as a starting point and should be reviewed before publishing. You are solely responsible for the content you publish using our Service. Blastly does not guarantee the accuracy, completeness, or suitability of AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">You retain ownership of the content you create using Blastly. By using the Service, you grant Blastly a limited licence to process your content solely for the purpose of providing the Service. The Blastly platform, logo, and all associated software remain the property of Blastly.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">Blastly shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability to you shall not exceed the amount paid by you to Blastly in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">We reserve the right to suspend or terminate your account if you violate these Terms. You may cancel your subscription at any time through your account settings. Upon termination, your access to the Service will cease.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">We may update these Terms from time to time. We will notify you of significant changes via email or through the Service. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">11. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">If you have questions about these Terms, please contact us at <Link href="/contact" className="text-blue-600 hover:underline">our contact page</Link> or email hello@blastly.ai.</p>
          </section>
        </div>
      </div>

      <footer className="border-t py-8 text-center text-sm text-muted-foreground mt-12">
        <div className="container flex flex-col md:flex-row items-center justify-between gap-4">
          <Link href="/"><img src="/manus-storage/blastly-icon-512_d2809e7c.png" alt="Blastly" className="h-8 w-auto object-contain" /></Link>
          <div className="flex gap-6">
            <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/contact" className="hover:text-foreground transition-colors">Contact</Link>
          </div>
          <p>© 2026 Blastly. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
